### ISSUE TITLE
关于eventfd，glib事件循环，bottomhalf的关系？

### ISSUE THREAD

**Issue by caisan** [newfriday/misc#5]
hi，看了博客中关于qemu事件循环的描述，不过还是有点不太清楚这三个之间的关系。这三个是独立的吗？还是说用某一个经过封装实现了另一个？
可以说明下吗？

**Comment by newfriday** [comment]
eventfd: 是实现线程通信的一个机制，见另一篇博客https://blog.csdn.net/huang987246510/article/details/103751172
glib事件循环：是一个通用的事件触发应用的框架，它用glibc的接口实现事件触发。
bottom half：qemu利用事件循环机制，向qemu内存的其它组件提供的一个异步调用的接口。因为其它组件运行可能不在主线程，但它想把自己注册的函数让qemu的主线程运行，就调用bottom half

**Comment by caisan** [comment]
> eventfd: 是实现线程通信的一个机制，见另一篇博客https://blog.csdn.net/huang987246510/article/details/103751172
> glib事件循环：是一个通用的事件触发应用的框架，它用glibc的接口实现事件触发。
> bottom half：qemu利用事件循环机制，向qemu内存的其它组件提供的一个异步调用的接口。因为其它组件运行可能不在主线程，但它想把自己注册的函数让qemu的主线程运行，就调用bottom half

感谢解答。
