### ISSUE TITLE
请教下qemu中virtqueue_pop()函数调用virtqueue_map_desc的问题

### ISSUE THREAD

**Issue by caisan** [newfriday/misc#6]
hi，看了这篇博客，https://blog.csdn.net/huang987246510/article/details/103708461#_2
有一个问题，virtio前端virtqueue_add()函数放到vring中的是desc在Guest中的GPA，同时QEMU中接收到的也是GPA。
那么qemu的virtqueue_pop()函数调用virtqueue_map_desc，进行GPA到HVA转换的时候，相当于处理的是同一个物理内存地址上的数据，只不过在QEMU和Guest中使用不同的地址来表示对吧？
能详细说下virtqueue_map_desc是如何将GPA转换为HVA的过程吗？thx ：）

**Comment by newfriday** [comment]
qemu在为虚机分配内存的时候，就有数据结构维护hva和gpa的关系，qemu是内存分配者，查自己维护的数据结构就可以知道。
具体原理可以看这里。
https://blog.csdn.net/huang987246510/article/details/104012839

偶尔翻到这收件箱，回复有点儿晚。希望可以帮助你理解。

















在 2020-07-07 11:48:23，"caisan" <notifications@github.com> 写道：

hi，看了这篇博客，https://blog.csdn.net/huang987246510/article/details/103708461#_2
有一个问题，virtio前端virtqueue_add()函数放到vring中的是desc在Guest中的GPA，同时QEMU中接收到的也是GPA。
那么qemu的virtqueue_pop()函数调用virtqueue_map_desc，进行GPA到HVA转换的时候，相当于处理的是同一个物理内存地址上的数据，只不过在QEMU和Guest中使用不同的地址来表示对吧？
能详细说下virtqueue_map_desc是如何将GPA转换为HVA的过程吗？thx ：）
